### ISSUE TITLE
README?

### ISSUE THREAD

**Issue by timholy** [HolyLab/StitchDPI.jl#2]
Could we get a brief summary of what this package is for? Maybe include a citation of the paper?

**Comment by Cody-G** [comment]
Working on it, and I'm finishing up polishing all other packages relevant to the paper, collected [here](https://github.com/HolyLab/FastScanningAndDPI) (that's the link we provide in the manuscript).  That repo is still private for now but I'm planning to open it when the paper is published, and to add links when the manuscript goes online.
